#!/bin/bash

# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!

#SBATCH --partition=computelong,computelong_intel
#SBATCH --job-name=DistSomaFunc
#SBATCH --array=1-(cat params.txt | wc -l)
#SBATCH --output=Futures_Parallel/%x-%A-%a.out

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G


#SBATCH --time=14-00:00:00     ### Wall clock time limit in Days-HH:MM:SS
#SBATCH --account=tau  ### Account used for job submission

#SBATCH --mail-type=all
#SBATCH --mail-user=mtrappet@uoregon.edu


source /home/mtrappet/BranchNetwork/data-science/bin/activate
params=$(sed -n "${SLURM_ARRAY_TASK_ID}p" params.txt)

python LongLearning.py $params